//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GridPartialPath {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GridPartialPath() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GridPartialPath", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Areas/Manage/Views/EventTypes/_grid.cshtml.
        /// </summary>
        internal static string EventTypes {
            get {
                return ResourceManager.GetString("EventTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Areas/Manage/Views/EventTypes/_gridAdd.cshtml.
        /// </summary>
        internal static string EventTypesAdd {
            get {
                return ResourceManager.GetString("EventTypesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Areas/Manage/Views/EventTypes/_gridButtons.cshtml.
        /// </summary>
        internal static string EventTypesButtons {
            get {
                return ResourceManager.GetString("EventTypesButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Areas/Manage/Views/EventTypes/_gridFaIcon.cshtml.
        /// </summary>
        internal static string FaIcon {
            get {
                return ResourceManager.GetString("FaIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Partials/_schedullerView.cshtml.
        /// </summary>
        internal static string Scheduller {
            get {
                return ResourceManager.GetString("Scheduller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Areas/Manage/Views/Territories/_grid.cshtml.
        /// </summary>
        internal static string Territories {
            get {
                return ResourceManager.GetString("Territories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Areas/Manage/Views/Territories/_gridAdd.cshtml.
        /// </summary>
        internal static string TerritoriesAdd {
            get {
                return ResourceManager.GetString("TerritoriesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Areas/Manage/Views/Territories/_gridButtons.cshtml.
        /// </summary>
        internal static string TerritoryButtons {
            get {
                return ResourceManager.GetString("TerritoryButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Areas/Manage/Views/Users/_gridButtons.cshtml.
        /// </summary>
        internal static string UserButtons {
            get {
                return ResourceManager.GetString("UserButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Areas/Manage/Views/Users/_grid.cshtml.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Areas/Manage/Views/Users/_gridAdd.cshtml.
        /// </summary>
        internal static string UsersAdd {
            get {
                return ResourceManager.GetString("UsersAdd", resourceCulture);
            }
        }
    }
}
